x = -5:5;
x_n = (-1).^x ;
h = -3:1;
h_n = ones(1,length(h));
y_n = conv(x_n,h_n);
y = x(1)+ h(1) + (0:length(y_n)-1);
figure;
subplot(3,1,1);
stem(x,x_n,'filled');
title('Sequence (-1)^n');
xlabel('n');
ylabel('Amplitude');
subplot(3,1,2);
stem(h,h_n,'filled');
title('Unit Pulse Sequence (-3 to 1)');
xlabel('n');
ylabel('Amplitude');
subplot(3,1,3);
stem(y,y_n,'filled');
title('Convoluted Sequence');
xlabel('n');
ylabel('Amplitude');
