f = 0.9;
x = 0:20;
x_n = sin(2*pi*f*x);
h = -18 : 14 ;
h_n = (-1).^h ;
y_n = conv(x_n,h_n);
y = x(1)+ h(1) + (0:length(y_n)-1);
figure;
subplot(3,1,1);
stem(x,x_n,'filled');
title('sin(2\pi fn) with frequency f = 0.9Hz');
xlabel('n');
ylabel('Amplitude');
subplot(3,1,2);
stem(h,h_n,'filled');
title('Sequence (-1)^n');
xlabel('n');
ylabel('Amplitude');
subplot(3,1,3);
stem(y,y_n,'filled');
title('Convoluted Sequence');
xlabel('n');
ylabel('Amplitude');